services:
  jellyseerr:
    image: fallenbagel/jellyseerr:latest
    container_name: jellyseerr
    environment:
      - LOG_LEVEL=debug
      - TZ=Etc/UTC
    volumes:
      - /JELLYSERR_CONFIG:/app/config
    ports:
      - "5055:5055"
    restart: unless-stopped
