services:
  navidrome:
    image: deluan/navidrome:latest
    user: 0:0
    ports:
      - "4533:4533"
    restart: unless-stopped
    volumes:
      - /NAVIDROME_DATA:/data
      - /NAVIDROME_MUSIC:/music:ro
