services:
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - WEBUI_PORT=8080
      - TORRENTING_PORT=8081
    volumes:
      - /QBITTORRENT_CONFIG:/config
      - /QBITTORRENT_DOWNLOADS:/downloads
    ports:
      - 8080:8080
      - 8081:8081
      - 8081:8081/udp
    restart: unless-stopped
