services:
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /RADARR_CONFIG:/config
      - /RADARR_MOVIES:/movies
      - /RADARR_DOWNLOADS:/downloads
    network_mode: host
    restart: unless-stopped
