services:
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /SONARR_CONFIG:/config
      - /SONARR_TV:/tv
      - /SONARR_DOWNLOADS:/downloads
    network_mode: host
    restart: unless-stopped
